# Generated by Django 6.0.2 on 2026-07-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoarduino',
            options={'verbose_name': 'Configuração do Arduino', 'verbose_name_plural': 'Configuração do Arduino'},
        ),
    ]
