# Generated by Django 6.0.5 on 2026-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hardware', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('horario_aberto', models.TimeField()),
                ('horario_fechado', models.TimeField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('MANUTENCAO', 'Em Manutenção')], default='FECHADA', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
